### ISSUE TITLE
Fix google-plus-alt SVG

### ISSUE THREAD

**Issue by andpiazza** [Automattic/Genericons#110]
**Steps to reproduce the issue**
Genericons SVG and TTF file for Google Plus Alt icon (\f218) is the same for Google Plus icon is (\f206)

**What I expected**
Google Plus Alt icon (\f218) to be different from Google Plus icon is (\f206)

**What happened instead**
Google Plus Alt icon (\f218) to the same as Google Plus icon is (\f206)

**Comment by jasmussen** [comment]
Genericons is unfortunately no longer being updated. Please see #106 for a few options!

**Comment by andpiazza** [comment]
Hello @jasmussen: I understand Genericons is deprecated per #106 
**Issue**: I don't understand how to use Genericons Neue or Social Logos when Jetpack invokes Genericons for Social Media Icons on sidebar: https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/
**Question**: I assume Jetpack code needs to update the fonts used. Then I'll be able to properly use Genericons Neue or Social Logos on the widget. Am I missing something?

**Comment by jasmussen** [comment]
I believe Jetpack is moving towards using "Social Logos", if it hasn't already. In any case, I would suggest you ask in the Jetpack repository: https://github.com/Automattic/jetpack — I'm sure someone there can help you!

**Comment by andpiazza** [comment]
thanks @jasmussen conversation ongoing: https://github.com/Automattic/jetpack/issues/9881
