### ISSUE TITLE
I can't find the Mastodon icon in the set 

### ISSUE THREAD

**Issue by jan-vandenberg** [Automattic/Genericons#114]
There is no Mastodon icon in the set?

**Comment by jasmussen** [comment]
The project is more or less on pause at this poin, and I think could be archived. You can maybe look at https://github.com/Automattic/gridicons/ paired with https://github.com/Automattic/social-logos?

**Comment by jan-vandenberg** [comment]
Thanks @jasmussen I figured this might be the case. I'll try and ping the maintainer of my WordPress theme with this info (the thing is the theme -- Independent Publisher -- does not support this).

**Comment by nitinthewiz** [comment]
@jan-vandenberg I'm also using Independent Publisher. Did you find a solution to this?

**Comment by jan-vandenberg** [comment]
No sorry I have not.
