### ISSUE TITLE
No more logos, social icons, service icons

### ISSUE THREAD

**Issue by jasmussen** [Automattic/Genericons#54]
One of the goals of Genericons is to keep it light-weight. This goal is incompatible with the idea that we keep adding logos for every social network out there. There are probably too many already, but there has to be a cutoff point, otherwise how do we weigh which we add and which we don't? It enters bloat area.

Genericons recently moved to use a font-baking commandline tool called FontCustom. In the next release SVG source files for every icon currently in genericons, as well as FontCustom metadata files, will be added in a source directory. This will make it trivial to build your own version of Genericons, just a matter of typing `fontcustom compile` in a terminal. At this point, Genericons forks on Github could potentially go in a different direction with more social icons, or perhaps none at all, or perhaps social icon only builds.

For those reasons, we will be adding no more logos or social icons to Genericons.

Please consider using a set like Social Logos instead: https://github.com/Automattic/social-logos

**Comment by Anatolt** [comment]
sad without vk

**Comment by wkwkrnht** [comment]
I want to use icons Line & Hatena bookmark.

**Comment by jasmussen** [comment]
Closing this in favor of #106, which is a shorter and more concise suggestion for where to go next.
