### ISSUE TITLE
Where's the 'font' folder?

### ISSUE THREAD

**Issue by jgresalfi** [Automattic/Genericons#59]
Hello - trying to install Genericons and all instructions mention a "font" folder. All I get with the .zip is a source folder with the .svgs. I could be missing something right in front of me. Any help would be appreciated!

**Comment by jasmussen** [comment]
Yep. My bad. The "font" folder has been renamed "genericons". It's in the same directory as the source folder. I will keep this ticket open as a reminder to myself to fix the instructions, thanks.

**Comment by jgresalfi** [comment]
Thanks very much for the quick reply. Cheers - Jason
