### ISSUE TITLE
How do we install this?

### ISSUE THREAD

**Issue by niji111** [Automattic/Genericons#63]
Ok this is a bummer but really.. how do i install Genericons?

Everywhere, including README.md says:
` ## Usage
To use it, place the `font` folder in.........`
But there is no 'fonts' folder in downloaded content!

Checking release notes directed me to 'http://fontcustom.com'. This site says output directory is '/path/to/vectors/fontcustom'. Now we do have 'genericons\source\fontcustom-templates'. Are these the same?

Now really.. how do we install?

Edit:
Ok sorry the answer is right here on: https://github.com/Automattic/Genericons
May i suggest updating README.md with the right information in this ticket so its clear for users with downloaded material only.

**Comment by Ipstenu** [comment]
> To use it, place the genericons folder in your stylesheet directory and enqueue the genericons.css file. 

Been like that for 2 months in Readme.md - where did you get that other than the notes for Photoshop?

> The Genericons.ttf file found in the font directory can be placed in your system fonts folder and used Photoshop or other graphics apps if you like.

Which needs to be updated, but that's not in "Usage"
