### ISSUE TITLE
Icons for Accessibility (Contrast + Larger/Smaller fonts)

### ISSUE THREAD

**Issue by MichaelVanDenBerg** [Automattic/Genericons#66]
Hi there!

I'm not sure, but I think a contest and larger/smaller font icons can be a useful addition.

See this page for an example (left side):
https://a11y.commons.mla.org/2014/01/14/make-your-wordpress-site-more-accessible/

Regards,

Michael

**Comment by jasmussen** [comment]
Hi there! I'm a big fan of making things accessible, always open to suggestions.

I need some more context to understand what you're suggesting for Genericons, though. I tried the button on the left side, that made everything larger, lovely. 

Genericons by virtue of being an icon font is already prepared for features like that, though — as you scale icons up, they stay crisp and sharp. Can you elaborate on your suggestion?

**Comment by MichaelVanDenBerg** [comment]
Yes, of course! I don't mean the effect when you click on them; I meant the icons themselves.

I'm not sure if there is any need for this, but if I wanted to make my site more accessible and if I wanted to do so by providing buttons to crank up the contrast or enlarge the fonts, there are no specific Genericons I could use. 

Yes, I could probably use an alternative like Bold (f471). But still... :)

**Comment by jasmussen** [comment]
Ooh I see, you'd like icons for increasing the size I see! Could you do something like:

<strong>A<sup>+</sup></strong> / <strong>A<sup>-</sup></strong>

for increasing/decreasing?

**Comment by jasmussen** [comment]
Closing for now.
