### ISSUE TITLE
dont need all genericons

### ISSUE THREAD

**Issue by Basti10** [Automattic/Genericons#73]
hello
I want to use Wordpress with the current theme 2015, which contains your genericons, but I do not need all genericons.
I've edited the svg and removed everything that I need. (my Website should load fast)
But how can I get individual ttf, eot and woff files and the  base64 encoded code?

**Comment by jasmussen** [comment]
Please see section "Building your own Genericons" in the readme.txt :)

https://github.com/Automattic/Genericons#building-your-own-genericons
