### ISSUE TITLE
What happened to /f423?

### ISSUE THREAD

**Issue by phoenixenero** [Automattic/Genericons#75]
Also known as the 404 character.

When using the Glyphs panel, I saw this (undocumented) icon:

![404 icon](http://puu.sh/jzMVd/5c95f5591b.png)

Is there any reason why it is not shown in the [genericons.com](http://genericons.com) website?

**Comment by jasmussen** [comment]
It's an easter-egg :)

It's featured on the 404 page of websites running the Twenty Thirteen theme, for which the icon-font was initially built.

**Comment by phoenixenero** [comment]
Oh nice! Didn't realize that :)

**Comment by jasmussen** [comment]
:)
