### ISSUE TITLE
Generic Icons

### ISSUE THREAD

**Issue by dshanske** [Automattic/Genericons#77]
Looking at the sorts of things people are suggesting, wondering if the following generic icons might work.
1. A musical note, indicating music
2. A knife and fork, indicating food.
3. A cup or mug indicating drink.
4. A joystick indicating game play.

I considered proposing something exercise related, because I saw someone was looking for Runkeeper, but I can't think of what symbolizes exercise in general.

**Comment by jasmussen** [comment]
Please consider [Genericons Neue](https://github.com/Automattic/genericons-neue) :)
