### ISSUE TITLE
No need for two kinds of facebook and linkedin icons

### ISSUE THREAD

**Issue by sunipeyk** [Automattic/Genericons#81]
Hello,
There is two kinds of facebook and linkedin icons you have in the collection. May be no need of the framed ones, because people can do it the framed one with css if they want to or need to. And you can add two another more icons instead of them. Just an idea.
Thank you.

**Comment by jasmussen** [comment]
We'll be de emphasising social logos further in the future, which will fix this. See also, #54 with alternatives. Thanks.
