### ISSUE TITLE
Behance icon missing

### ISSUE THREAD

**Issue by kevinmamaqi** [Automattic/Genericons#86]
Behance is one of the most used creative networks and I think is a must for all the creatives that uses WordPress as a portfolio/service website.

Is it possible to add it?

**Comment by DouglasdeMoura** [comment]
Check https://github.com/Automattic/Genericons/issues/54

**Comment by kevinmamaqi** [comment]
I know, fontello has been available for a while and out there are hundreds of free icons. The point is that Behance is the leading portfolio platform for all kind of creatives. I think it is a must for an excellent an 'minimalist' font such as genericons.

**Comment by kevinmamaqi** [comment]
BTW, everything clear and issue closed.
