### ISSUE TITLE
add tags for every released version

### ISSUE THREAD

**Issue by maruilian11** [Automattic/Genericons#89]
hi, we recently want to add your lib on https://cdnjs.com, could you please add git tags for each release version so that we can update the lib with **git auto-update config**.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7231

**Comment by jasmussen** [comment]
Genericons is sort of on hiatus pending new developments in the icon font space. As it stands, <a href="https://bugs.chromium.org/p/chromium/issues/detail?id=426333">Chrome has some bugs that makes icon fonts less desirable to use</a>. However, yes, we'll be sure to tag possible future releases!

**Comment by maruilian11** [comment]
thank you!
