### ISSUE TITLE
Right and Left arrows for slider

### ISSUE THREAD

**Issue by JamesGeiger** [Automattic/Genericons#9]
Can these be added?

**Comment by buffler** [comment]
This is way after the fact, but you could use the following to get something like what (I think) you were looking for:

```
.genericon-expand,
.genericon-collapse {
  -webkit-transform: rotate(90deg);
      -ms-transform: rotate(90deg);
          transform: rotate(90deg);
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
}
```

That ends up looking something like this:

![rotated-genericons](https://cloud.githubusercontent.com/assets/890142/9286579/413a9286-42ab-11e5-8048-ea7c11c2a4f8.png)

(and of course you could add more transforms if you wanted to further tweak by skewing/stretching/etc.)
