### ISSUE TITLE
Email Icon Missing

### ISSUE THREAD

**Issue by JMarriott76** [Automattic/Genericons#91]
The release notes (3.02) mention the email icon ("The email icon has been updated for style and clarity, and to fit with the new subscribe icons.") but it now appears to be missing. Was it removed? If not, what is the code for it?

**Comment by jasmussen** [comment]
I'm not seeing this — the mail icon is still in the set, looks like this:

![screen shot 2016-04-25 at 08 39 24](https://cloud.githubusercontent.com/assets/1204802/14775698/3f4227ee-0ac1-11e6-8bae-b3663d4cdc77.png)

**Comment by JMarriott76** [comment]
"E" mail / "Email". Electronic mail. NOT regular mail.

**Comment by jasmussen** [comment]
Understood. But that's the icon Genericons has for electronic mail.
