### ISSUE TITLE
Is there genericons npm module which i can use?

### ISSUE THREAD

**Issue by ohmirocks** [Automattic/Genericons#96]

**Comment by jasmussen** [comment]
I don't think there is one, but there probably should be.

**Comment by ohmirocks** [comment]
i am planning to create one and use it. Let me know if thats ok

**Comment by jasmussen** [comment]
It's likely that the next version of Genericons will not have a clean upgrade path (see <a href="https://github.com/Automattic/Genericons/tree/refactor/genericons">preview here</a>), that would be the only reason to wait.

**Comment by ohmirocks** [comment]
totally agree, I just published one in mean while for us to use. Once we have next generation we can find a easy upgrade path.

**Comment by jasmussen** [comment]
Hi @ohmirocks, I just published [Genericons Neue](https://github.com/Automattic/genericons-neue), a refresh of Genericons. I'm planning to make that an npm module, but not Genericons. Feel free to have a look.
