### ISSUE TITLE
Please add Medium icon

### ISSUE THREAD

**Issue by davorg** [Automattic/Genericons#97]
Hi,

It would be great to have the Medium icon included. I might see if I can create a pull request for this over the next few days - unless someone is already working on it.

Thanks,

Dave...

**Comment by jasmussen** [comment]
We've wound down the inclusion of logos, I'm afraid. Please consider using this instead: https://github.com/Automattic/social-logos

**Comment by davorg** [comment]
Ah. I see. But unfortunately, the TwentySixteen theme still uses Genericons for icons on its social media menu :-(

I suppose I need to suggest that they switch to social-logos instead.

Thanks for the reply.
