### ISSUE TITLE
Links in README.md and fontcustom.yml redirect to an expired domain on auction

### ISSUE THREAD

**Issue by rsp** [Automattic/Genericons#99]
The FontCustom domain has expired - see FontCustom/fontcustom#298
PR #92 changed the fontcustom.com links in README.md and source/fontcustom.yml to http://fontcustom.github.io/fontcustom but this new URL still redirects to the expired domain.

The project's website is there (see my fork at https://rsp.github.io/fontcustom/) but because it includes a CNAME file with the old domain, users get redirected and don't see it.

I made a PR FontCustom/fontcustom#312 removing the CNAME file in the project gh-pages branch to avoid the redirection. Meanwhile before it gets accepted I'm letting you know that you have links in your documentation that don't point to where you think they do.

**Comment by jasmussen** [comment]
Fixed in #100.
